### ISSUE TITLE
组件可以单独引入吗

### ISSUE THREAD

**Issue by wizard-a** [gantFDT/gant-design#2]

**Comment by yuanguandong** [comment]
部分组件是独立的包，比如data-cell-g, 可以只安装data-cell-g即可
如果安装了gantd, 使用gantd里面的组件也是按需加载的，
```
const extraBabelPlugins = [
  [
    "import",
    {
      "libraryName": "gantd",
      "libraryDirectory": "lib",
      "style": "css"
    }
  ]
]
```

**Comment by wizard-a** [comment]
嗯嗯，我看到了按需加载，也都跑起来了，现在引入组件会覆盖原先的 antd 样式 。菜单我在项目里做过自定义配置，但 gantd 好像又改了一些。这个有解决办法吗 ?
我目前想到的是把你的仓库给 fork出来，自己改，但你仓库更新其它功能，我在合并这也是一个痛苦的过程

引入之前

![image](https://user-images.githubusercontent.com/9709396/80582540-7c3b7480-8a41-11ea-801f-7e46859b526e.png)


引入之后
![image](https://user-images.githubusercontent.com/9709396/80582423-43030480-8a41-11ea-9dfd-0aca0d4bfaad.png)
