### ISSUE TITLE
咨询个问题啊，SmartGrid与Grid在使用场景上有什么区别吗?求科普

### ISSUE THREAD

**Issue by xamarinOfCai** [gantFDT/gant-design#6]
如题，我看了[SmartGrid的文档](https://docs.gant.design/?path=/story/%E7%BB%84%E4%BB%B6-%E5%88%97%E8%A1%A8--smartgrid-%E6%99%BA%E8%83%BD%E8%A1%A8%E6%A0%BC-%F0%9F%93%A6)和相应的Grid的文档后，有个疑惑啊，这两个Grid在使用的业务场景有啥区别吗？SmartGrid看是Grid的的plus的版本，它重点解决Grid中哪些不支持的业务场景啊？对于我们平常的业务场景的选择，有啥建议吗，多谢

**Comment by xamarinOfCai** [comment]
还有个问题啊，SmartGrid上面的Demo，示例展示的与下面的源代码对不上啊
![image](https://user-images.githubusercontent.com/44486733/156959858-966e223c-d33b-4c9b-9218-07bcdcdaa867.png)
![image](https://user-images.githubusercontent.com/44486733/156959949-9e00a17a-08cc-44d6-9afa-4cde79df0b25.png)

**Comment by yuanguandong** [comment]
> 如题，我看了[SmartGrid的文档](https://docs.gant.design/?path=/story/%E7%BB%84%E4%BB%B6-%E5%88%97%E8%A1%A8--smartgrid-%E6%99%BA%E8%83%BD%E8%A1%A8%E6%A0%BC-%F0%9F%93%A6)和相应的Grid的文档后，有个疑惑啊，这两个Grid在使用的业务场景有啥区别吗？SmartGrid看是Grid的的plus的版本，它重点解决Grid中哪些不支持的业务场景啊？对于我们平常的业务场景的选择，有啥建议吗，多谢

你好，感谢对gantd的关注，就目前来讲，smartGrid相比于grid增加了视图的概念，用户可以自定义列的各种状态并保存到本地存储或者远端，解决的是不同的用户或角色对业务关注点不同的痛点。
对于使用来讲，如果是grid能满足需求就不用smartGrid
目前gantd还不成熟，很抱歉对于smartGrid的文档和示例匹配不上，grid目前的示例应该是匹配的 🤝

**Comment by xamarinOfCai** [comment]
> 

多谢！
